"use client";

import { ChangeEvent, useState } from "react";

import { useRecoilState, useResetRecoilState } from "recoil";

import {
  BottomGradient,
  EMI,
  Layout,
  LoanRepaymentScheduleTable,
  PaymentBreakUp,
  TextField,
} from "@/components";
import { useRecoilValue } from "recoil";

import { OutcomeProps } from "@/types";
import { toCurrency } from "@/utils";

import { CURRENCY_SYMBOL } from "@/constants";
import { calculateEmiOutcome, validateForm } from "@/utils";

import stateAtom from "@/atoms/stateAtom";
import Link from "next/link";

export default function Home() {
  const [state, setState] = useRecoilState(stateAtom);
  const resetState = useResetRecoilState(stateAtom);
  const [netIncome, setNetIncome] = useState(0);
  const [discountRate, setDiscountRate] = useState(0);
  const [time, setTime] = useState(0);
  const { loanAmount, interestRate, loanTenure, prepayments, errors } = state;
  const [result, setResult] = useState(0);
  const onInputChange = (e: ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;

    setState({ ...state, [name]: value });
  };
  const onresetState = () => {
    setDiscountRate(0);
    setNetIncome(0);
    setTime(0);
    setResult(0);
  };
  const onCalculate = () => {
    if (netIncome !== 0 && discountRate !== 0 && time !== 0) {
      const data = netIncome / Math.pow(1 + discountRate, time);
      setResult(data);
    }
  };

  const resetStatus = netIncome !== 0 || discountRate !== 0 || time !== 0;
  const { outcome } = useRecoilValue(stateAtom);
  const tabs = [
    {
      title: "Exponential Decline",
      content: <div>Content for Tab 1</div>,
    },
    {
      title: "Harmonic Decline",
      content: <div>Content for Tab 2</div>,
    },
    {
      title: "Hyperbolic Decline",
      content: <div>Content for Tab 3</div>,
    },
  ];
  return (
    <Layout>
      <main>
        <div className="relative px-6 lg:px-8">
          <div className="mx-auto max-w-2xl py-4 sm:py-8 lg:py-12">
            <h1 className="text-center text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
              Petroleum Project Calculator
            </h1>
            <p className="text-center mt-6 text-lg leading-8 text-gray-600">
              An NPV (Net Present Value) calculator is a financial tool used to
              estimate the present value of all future cash flows generated by
              an investment or project, considering the time value of money. It
              takes into account factors such as the initial investment,
              expected cash inflows, discount rate, and the duration of the
              investment to determine whether the investment is expected to
              generate positive or negative returns when discounted back to the
              present.
            </p>
            <div className="flex items-center justify-center w-full">
              <Link
                href="/production-calculator"
                className="rounded-xl border border-solid border-sky-500 bg-background-button-secondary flex items-center justify-center py-2 px-4 font-medium text-captionL text-text-base-primary mt-5"
              >
                Go to Calculator
              </Link>
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
}
